---
kind: pipeline
name: dev

platform:
  os: linux
  arch: amd64

clone:
  disable: true
  skip_verify: true

steps:
  - name: sync-code
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key_dev
      SSH_FINGERPRINT:
        from_secret: ssh_fingerprint
    commands:
      - mkdir /root/.ssh 
      - echo -n "$SSH_KEY" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "$SSH_FINGERPRINT" > /etc/ssh/ssh_known_hosts
      - wc -c ~/.ssh/id_rsa
      - wc -c /etc/ssh/ssh_known_hosts
      - git clone --depth 1 git@192.168.5.10:customer-jfyz/jfindx-wms-official-ui.git -b ${DRONE_COMMIT_SHA} /drone/src

  - name: publish
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_dev_username
      password:
        from_secret: docker_dev_password
      registry:
        from_secret: docker_dev_registry
      repo:
        from_secret: docker_dev_repo
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH//\//-}
        - dev
      build_args:
        - MILLET_BUILD_ARG=dev
    depends_on:
      - sync-code

  - name: deploy
    image: dockerhub.milletcode.com/carbon/deploy-bot
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_dev_api
      kubernetes_token:
        from_secret: kube_dev_token
      kubernetes_cert:
        from_secret: kube_dev_cert
      repo:
        from_secret: docker_dev_repo
      namespace: studio
      deployment: jfindx-wms-official-ui-dev
      container: jfindx-wms-official-ui
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish

volumes:
  - name: cache
    host:
      path: /mnt/data/drone-build/jfindx/jfindx-wms-official-ui/node_modules

trigger:
  branch:
    - dev

---
kind: pipeline
name: jfindx

platform:
  os: linux
  arch: amd64

clone:
  disable: true
  skip_verify: true

steps:
  - name: sync-code
    image: alpine/git
    environment:
      SSH_KEY:
        from_secret: ssh_key_dev
      SSH_FINGERPRINT:
        from_secret: ssh_fingerprint
    commands:
      - mkdir /root/.ssh 
      - echo -n "$SSH_KEY" >> ~/.ssh/id_rsa
      - chmod 600 ~/.ssh/id_rsa
      - echo "$SSH_FINGERPRINT" > /etc/ssh/ssh_known_hosts
      - wc -c ~/.ssh/id_rsa
      - wc -c /etc/ssh/ssh_known_hosts
      - git clone --depth 1 git@192.168.5.10:customer-jfyz/jfindx-wms-official-ui.git -b ${DRONE_COMMIT_SHA} /drone/src


  - name: publish
    image: plugins/docker
    daemon_off: true
    privileged: true
    settings:
      username:
        from_secret: docker_jfindx_username
      password:
        from_secret: docker_jfindx_password
      registry:
        from_secret: docker_jfindx_registry
      repo:
        from_secret: docker_jfindx_repo
      tags:
        - ${DRONE_COMMIT_SHA}
        - ${DRONE_COMMIT_BRANCH//\//-}
        - jfindx
      build_args:
        - MILLET_BUILD_ARG=production
    depends_on:
      - sync-code

  - name: deploy
    image: dockerhub.milletcode.com/carbon/deploy-bot
    daemon_off: true
    privileged: true
    settings:
      kubernetes_server:
        from_secret: kube_jfindx_api
      kubernetes_token:
        from_secret: kube_jfindx_token
      kubernetes_cert:
        from_secret: kube_jfindx_cert
      repo:
        from_secret: docker_jfindx_repo
      namespace: studio
      deployment: jfindx-wms-official-ui-jfindx
      container: jfindx-wms-official-ui
      tag: ${DRONE_COMMIT_SHA}
    depends_on:
      - publish

volumes:
  - name: cache
    host:
      path: /mnt/data/drone-build/jfindx/jfindx-wms-official-ui/node_modules

trigger:
  branch:
    - master
